### ISSUE TITLE
General escrow: receiver/sender terms confusion

### ISSUE THREAD

**Issue by jaybuidl** [kleros/escrow-v2#19]
## Rationale
There is obvious way to know if receiver/sender is from the point of view of either the _goods/service provider_ or either the _customer_ which leads to confusion.

## Solution
In the general escrow scenario, the terms _buyers_ and _sellers_ are more intuitive.

The current design assumes the point of view of the goods/service provider, therefore the terms map as follow: 
- **Receiver** [of a service/good] into **Buyer**
- **Sender** [of a service/good] into **Seller**

**Comment by kemuru** [comment]
fixed
